name: mineTeams
version: ${project.version}
main: pl.arturekdev.mineTeams.Teams
api-version: 1.16
authors: [ arturekdev ]
description: Minecraft teams
website: https://minecodes.pl
depend: [PlaceholderAPI]
commands:
  team:
    aliases:
      - teams
      - zespoly
      - zespol
